#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo '🏗️👷 Formatting and Linting before committing 👷‍♂️🏗️'
 
# Check ESLint and Prettier Standards
yarn lint-staged

echo '🎉 No error found: committing this now.... ✨🚀🏄‍♂️🍻'